# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7b05d16c3f59b35f650a99b1184b55f9bc995ef6ecb460414738efba4d126e09cb1795d25d1db93a291556e9a84f9abd343da9d9d28c65f58d91a4f7d95f6d

test:
  secret_key_base: c680d9739eb8d57d8ce55977d3a8c9d37aa854eeeb9fb30710a19a7803bf4458f35b9d7db4a5a1d948758a9062159911e55c30a16b7dd3f3169ac4e7d002f219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
